FROM wzg547228197/gluten:centos-8


RUN yum install -y java-17-openjdk-devel patch wget git perl
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
ENV PATH=$JAVA_HOME/bin:$PATH

ENV PATH=${PATH}:/usr/lib/maven/bin

RUN git clone https://github.com/kevinw66/incubator-gluten /opt/gluten
RUN cd /opt/gluten && git checkout origin/arm-ci

RUN if [ "$(uname -m)" = "aarch64" ]; then \
        export CPU_TARGET="aarch64"; \
        export VCPKG_FORCE_SYSTEM_BINARIES=1; \
    fi && \
    cd /opt/gluten && source /opt/rh/gcc-toolset-11/enable && ./dev/builddeps-veloxbe.sh --run_setup_script=ON build_arrow && rm -rf /opt/gluten

